#!/bin/sh
# /etc/init.d/vncboot


### BEGIN INIT INFO
# Provides:          vncserver 
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start VNC server at boot time 
# Description:       Start VNC server at boot time 
### END INIT INFO

USER=pi
HOME=/home/pi

case "$1" in
  start)
    echo "Starting VNC Server"
    su pi -c "/usr/bin/vncserver :0 -geometry 1280x800 -depth 16 -dpi 96"
    ;;
  stop)
    echo "Stopping VNC Server"
    /usr/bin/vncserver -kill :0
    ;;
  *)
  echo "Usage: /etc/init.d/vncboot {start|stop}"
  exit 1
  ;;
esac

exit 0
